export const RACKET_PHASE_DURATION_MS = 4000;
export const LOGO_PHASE_DURATION_MS = 2000;
export const LOGO_REVEAL_DURATION_MS = 350;
export const OVERLAY_EXIT_DURATION_MS = 600;
export const OVERLAY_EXIT_DELAY_MS =
  RACKET_PHASE_DURATION_MS + LOGO_PHASE_DURATION_MS;
export const OPENING_DURATION_MS =
  OVERLAY_EXIT_DELAY_MS + OVERLAY_EXIT_DURATION_MS;
export const ASSET_WAIT_LIMIT_MS = 1800;
export const OVERLAY_FAILSAFE_MS = 10000;
